[unstable]
# order cargo to re-compile "core" and "compiler_builtins" libraries.
# ("core" depends on "compiler_builtins")
build-std = ["core", "compiler_builtins"]

# activate 'memset', 'memcpy', 'memcmp' in 'compiler-builtins' libraries.
# (generally they are disable in order not to conflict those in C libraries)
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[build]
target = "x86_64-lemola_os.json"
